on:
  push:
    branches:
    - master
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_REGISTRY_LOGIN_SERVER: butcherapp.azurecr.io
  CONTAINER_APP_NAME: butcherapp
  CONTAINER_APP_RESOURCE_GROUP_NAME: DefaultResourceGroup-PAR
  CONTAINER_APP_CONTAINER_NAME: containerapp
  PROJECT_NAME_FOR_DOCKER: butcherapp
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Login to Azure container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.butcherapp_USERNAME_2F07 }}
        password: ${{ secrets.butcherapp_PASSWORD_2F07 }}
    - name: Build and push image to Azure container registry
      run: dotnet publish -c Release -r linux-x64 -p:PublishProfile=DefaultContainer -p:ContainerImageTag=${{ github.sha }} --no-self-contained -p:ContainerRegistry=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} -bl
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: binlog
        path: msbuild.binlog
  deploy:
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.butcherapp_SPN }}
    - name: Deploy to Azure container app
      uses: azure/CLI@v1
      with:
        inlineScript: >-
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.butcherapp_USERNAME_2F07 }} --password ${{ secrets.butcherapp_PASSWORD_2F07 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: Azure logout
      run: az logout
